---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: projects
  label: Projects
  create: documents
  match: "**/*.md"
  templates:
  - project
- type: directory
  path: case_studies
  label: Case studies
  create: documents
  match: "**/*.md"
  templates:
  - project
- type: document
  path: data/theme.json
  label: Theme config
upload_dir: anna-portfolio
public_path: https://simon-renault-dev-bucket.s3.eu-west-2.amazonaws.com/anna-portfolio
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
