---
label: Theme configuration
hide_body: true
fields:
- type: text
  name: site_name
  label: Site name
- type: textarea
  name: site_description
  label: Site description
- name: hero_title
  type: text
  config:
    required: false
  label: Hero title
- type: textarea
  name: hero_text
  config:
    wysiwyg: true
    schema:
      format: html
  label: Hero text
- name: copyright
  type: text
  hidden: false
  default: ''
  label: copyright
- type: boolean
  name: dark_mode
  label: Dark mode
- name: footer_title
  type: text
  config:
    required: false
  label: Footer title
- name: footer_text
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Footer text
pages:
- data/theme.json
